-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE public.cbondratingdefinition (
	object_id varchar(100) NULL,
	b_info_creditratingagency varchar(100) NULL,
	b_info_creditrating_name varchar(100) NULL,
	s_info_compcode varchar(100) NULL,
	opmode varchar(100) NULL,
	opdate varchar(100) NULL,
	mopdate varchar(100) NULL,
	data_tm varchar(100) NULL,
	tx_dt varchar(100) NULL
);

INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{12D244DA-4272-11EF-9E12-0C9D92659B8A}', '45', '埔柳妙社论天町海凯蓝伦攀伺放', 'KNVIHN4OCE', '0', '2024-07-15T14:28:55+08:00', '2024-07-15T14:19:32+08:00
', '20240715', '2024-07-15');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{096E517C-427A-11EF-95B0-FC3497B90A6D}', '46', 'SQIUIxtgldqBgkgtba', 'E24BB6', '0', '2024-07-15T15:45:53+08:00', '2024-07-15T15:38:58+08:00
', '20240715', '2024-07-15');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{D245D9CF-4E72-11EF-95BE-FC3497B90A6D}', '50', 'SIYJYBIxtgldqBgkgtba', '14WCK1E54J', '0', '2024-07-30T21:01:41+08:00', '2024-07-30T20:55:07+08:00
', '20240730', '2024-07-30');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{A862F218-427A-11EF-95B0-FC3497B90A6D}', '47', 'YSIQBgkgtba', 'E24D51', '0', '2024-07-16T17:50:25+08:00', '2024-07-16T17:41:21+08:00
', '20240716', '2024-07-16');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{2565B9C7-4358-11EF-95B2-FC3497B90A6D}', '48', 'RpgziumpiIxtgldqYlagxGpgtxtbBgkgtba', 'WkhztSYvrX', '0', '2024-07-16T17:50:25+08:00', '2024-07-16T17:46:20+08:00
', '20240716', '2024-07-16');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{8B473E6C-4FE7-11EF-95C0-FC3497B90A6D}', '51', 'YlagxIxtgldqxlaIbqbxpzeGpgtxtbBgkgtba', 'VVOGAEZVMT', '0', '2024-08-01T17:34:16+08:00', '2024-08-01T17:22:41+08:00
', '20240801', '2024-08-01');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{8605B2A9-DF96-4629-8EC3-F43C3609B6FB}', '15', '中国氛程监督管理委布妙', '502041739', '0', '2012-05-07T09:10:19+08:00', '2012-05-07T09:10:19+08:00
', '20231214', '2023-12-14');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{C7C50CE2-FD08-440D-9302-6C5AB3343644}', '10', '河南好炎疾武芮秀订', '2002584', '0', '2012-05-07T09:10:19+08:00', '2012-05-07T09:10:19+08:00
', '20231214', '2023-12-14');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{E55D4421-EE68-4559-87FD-F7069DD4109A}', '21', '天津懿倩炎芹服务闪财公司', '7yBTBPtExO', '0', '2013-07-26T09:47:10+08:00', '2013-07-26T09:47:10+08:00
', '20231214', '2023-12-14');
INSERT INTO public.cbondratingdefinition
(object_id, b_info_creditratingagency, b_info_creditrating_name, s_info_compcode, opmode, opdate, mopdate, data_tm, tx_dt)
VALUES('{D317AE43-61A6-4EC0-B493-758F7AE253CC}', '28', '池俞町好乒服务香港闪财公司', 'bB5TVX6g9I', '0', '2016-08-15T13:41:27+08:00', '2016-08-15T13:41:27+08:00
', '20231214', '2023-12-14');
