-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE public.cbondissuerrating (
	objct_id varchar(100) NULL,
	cocn_nm varchar(100) NULL,
	rat_dt varchar(100) NULL,
	rattyp varchar(100) NULL,
	crdtrat varchar(100) NULL,
	ratotlk varchar(100) NULL,
	ratinst_id varchar(100) NULL,
	bndsbjctco_id varchar(100) NULL,
	crdtratdscr varchar(100) NULL,
	prvcrdtrat varchar(100) NULL,
	ratchngdir varchar(100) NULL,
	ratobjcttyp_id varchar(100) NULL,
	anno_dt varchar(100) NULL,
	tx_dt varchar(100) NULL
);


INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{E8FA1A85-4596-11E7-B602-C03FD5700F97}', '华宝期货有限公司', '20160101', '4', 'BBB', NULL, '15', '1hS7EE462F', '公司风险管理能力、市场竞争力、培育和发展机构投资者状况、持续合规状况的综合评价在行业内较高，能够控制业务风险', 'A', '调低', '536002000', '20160805', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{43E20CB3-86F4-4992-A7E3-6163ACFE0648}', '华宝期货有限公司', '20150101', '4', 'A', NULL, '15', '1hS7EE462F', '公司风险管理能力、市场竞争力、培育和发展机构投资者状况、持续合规状况的综合评价在行业内最高，能够较好控制业务风险', 'A', '维持', '536002000', '20150820', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{E4BB558A-C0D4-11EF-977A-D45D64F20772}', '华宝期货有限公司', '20241029', '1', 'AA', '518003000', '2', '1hS7EE462F', '受评对象偿还债务的能力很强，受不利经济环境的影响较小，违约风险很低。', NULL, '首次', '536001001', '20241220', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{CAA540A8-5496-4941-8140-C8F1FA5A43FC}', '华宝期货有限公司', '20110101', '4', 'A', NULL, '15', '1hS7EE462F', '公司风险管理能力、市场竞争力、培育和发展机构投资者状况、持续合规状况的综合评价在行业内最高，能够较好控制业务风险', NULL, '首次', '536002000', '20110815', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{DF64A159-CD86-11EF-B28E-FC3497139286}', '浙江长兴金融控股集团有限公司', '20250107', '1', 'AA+', '518003000', '5', 'keuZWulaI8', NULL, 'AA+', '维持', '536001001', '20250108', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{62026DA4-CD86-11EF-970E-C8D9D229E390}', '江苏武进绿色建筑产业投资有限公司', '20250106', '1', 'AA', '518003000', '4', 'J55GrlvcMQ', '短期债务的支付能力和长期债务的偿还能力很强；经营处于良性循环状态，不确定因素对经营与发展的影响很小；偿还债务的能力很强，受不利经济环境的影响不大，违约风险很低。', 'AA', '维持', '536001001', '20250107', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{925AE2EC-CD93-11EF-9E6F-E89C250FD000}', '无锡市建设发展投资有限公司', '20250107', '1', 'A+', '518003000', '33', '15730C', '发行人违约概率低，偿债能力强。', 'A+', '维持', '536001001', '20250107', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{AE2E4C2B-182A-11EB-B166-C03FD5E52FFE}', '华宝期货有限公司', '20200101', '4', 'BBB', NULL, '15', '1hS7EE462F', '公司风险管理能力、市场竞争力、培育和发展机构投资者状况、持续合规状况的综合评价在行业内较高，能够控制业务风险', 'BBB', '维持', '536002000', '20201023', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{D124A833-2B7B-4D0D-B536-6A850894294F}', '华宝期货有限公司', '20140101', '4', 'A', NULL, '15', '1hS7EE462F', '公司风险管理能力、市场竞争力、培育和发展机构投资者状况、持续合规状况的综合评价在行业内最高，能够较好控制业务风险', 'BBB', '调高', '536002000', '20141023', '2025-01-08');
INSERT INTO public.cbondissuerrating
(objct_id, cocn_nm, rat_dt, rattyp, crdtrat, ratotlk, ratinst_id, bndsbjctco_id, crdtratdscr, prvcrdtrat, ratchngdir, ratobjcttyp_id, anno_dt, tx_dt)
VALUES('{2702B265-CD68-11EF-9F2D-D45D64F1DD45}', '江苏金融租赁股份有限公司', '20241230', '1', 'AAA', '518003000', '2', '45U9A7FA94', '受评对象偿还债务的能力极强,基本不受不利经济环境的影响,违约风险极低.', 'AAA', '维持', '536001001', '20250108', '2025-01-08');
